### ISSUE TITLE
libstatgrab 0.91, configure not find docbook2man

### ISSUE THREAD

**Issue by nemysis** [i-scream/libstatgrab#73]
I try to update in openSUSE libstatgrab from 0.17 to 0.91.

When wish to use Man Pages, which is very useful with

```
--enable-man-build
```

I have in spec

```
BuildRequires:  docbook-utils-minimal
BuildRequires:  docbook2x
```

What is in docbook-utils-minimal
```\n
rpm -ql docbook-utils-minimal

/usr/bin/docbook2html
/usr/bin/docbook2man
/usr/bin/docbook2rtf
/usr/bin/docbook2txt
/usr/bin/jw
/usr/bin/sgmldiff
...
```

Get with build

```\n
[   71s] checking for applicable docbook2man... none
[   71s] configure: error: Want manpages being build but have no docbook2man
[   71s] error: Bad exit status from /var/tmp/rpm-tmp.XIByIV (%build)
```

Could you correct this?

**Comment by rehsack** [comment]
Hi @nemysis ,

I'm sorry to tell you: your spec is possibly wrong:

1) For release versions you don't need to build the manuals, they're bundled
2) you need docbook2x - just the binaries are probably not enough. check config.log why the test fails.

Best regards,
Jens

**Comment by nemysis** [comment]
Thanks i have removed docbook-utils-minimal and Man Pages are installed.
