### ISSUE TITLE
A few comments

### ISSUE THREAD

**Issue by tobimensch** [i-scream/libstatgrab#80]
First of all, I'm sorry (not really though) for misusing the issues tracker to make a few comments.

1) It seems like there's a scarcity of libraries with the same general goals and possible use cases as libstatgrab. There's libsigar, which is unfortunately licensed under apache v2.0 and therefore can for example not be used in a GPLv2only program. There's supposed to be some extend of support for this in the ACE framework, but I can't trust a website/organization that looks like it is from 1995 (if anyone from the ACE framework is reading this, please take no offense, but your website really could use a makeover), and the documentation is bad to put it mildly. If there are other libraries/options that I've not come across yet, please let me know.

2) libsigar would have been the library of choice, if it hadn't been for the fact that apache v2.0 isn't GPLv2 compatible. What's missing in libstatgrab compared to libsigar is support for prominent OSs such as Windows and OSX.

3) libstatgrab's last release is from July 2014. When there has not been a release in 2 years, many people assume a project is dead, or at least not actively developed. Indeed looking at the commits not much has happened since the last release. However I'd still highly advise to make a release anyhow. Even if you just fix one line, or make only a single bug fix, doing a new minor release is a very good idea, because otherwise users will never enjoy this improvement (however little it may be), and the sense of a "dead" project will only increase. Developers will become hesitant to use a library with no progress at all, while even tiny releases can give the appearance of some progress. I think ESR is spot on https://en.wikipedia.org/wiki/Release_early,_release_often !

4) I would like to see support for Windows / MacOSX and more platforms. I want to use this library in https://github.com/tobimensch/aqemu . Is there any reason support for those platforms wasn't already added, besides that nobody has done the work?

5) I googled for "c c++ library process cpu mem usage" and similar terms, a few links and Stackoverflow threads came up, but libstatgrab was nowhere to be found. A helpful person on IRC made me aware of libstatgrab. It seems like libstatgrab's website and github page aren't optimized to be found by a search engine, yet. It would be a good idea to make mention of libstatgrab on those stackoverflow threads that came up, and I might do that later. I want to suggest working on the website, the github description and the README. Currently all the information that you're getting is "cross platform access to statistics about the system on which it's run". This isn't useful for search engine queries. You need to describe what kind of statistics exactly. For example "statistics about process cpu load and memory usage". Generally the more detailed a description you can give the better (it can be found).

**Comment by rehsack** [comment]
> Am 15.06.2016 um 12:23 schrieb Tobi <notifications@github.com>:
> 
> First of all, I'm sorry (not really though) for misusing the issues tracker to make a few comments.
> 
> 1) It seems like there's a scarcity of libraries with the same general goals and possible use cases as libstatgrab. There's libsigar, which is unfortunately licensed under apache v2.0 and therefore can for example not be used in a GPLv2only program. There's supposed to be some extend of support for this in the ACE framework, but I can't trust a website/organization that looks like it is from 1995 (if anyone from the ACE framework is reading this, please take no offense, but your website really could use a makeover), and the documentation is bad to put it mildly. If there other libraries/options that I've not come across yet, please let me know.

Well, please keep on one topic. I have no idea what the question/comment from that paragraph is - so I'm unable to give you any kind of serious answer.

> 2) libsigar would have been the library of choice, if it hadn't been for the fact that apache v2.0 isn't GPLv2 compatible. What's missing in libstatgrab compared to libsigar is support for prominent OSs such as Windows and OSX.

Than, please - use libsigar. We figured out for our use cases, that all information are reasonable delivered by libstatgrab.
And - depend on your point of view - AIX, HP-UX or Solaris are prominent OSs for large systems and *BSD's are prominent for rock stable appliances.
So, Desktop OSs aren't the only corner having prominent members :P

> 3) libstatgrab's last release is from July 2014. When there has not been a release in 2 years, many people assume a project is dead, or at least not actively developed.

Well, Google please what assumptions are good for.

>  Indeed looking at the commits not much has happened since the last release. However I'd still highly advise to make a release anyhow. Even if you just fix one line, or make only a single bug fix, doing a new minor release is a very good idea, because otherwise users will never enjoy this improvement (however little it may be), and the sense of a "dead" project will only increase. Developers will become hesitant of using a library with no progress at all, while even tiny releases can give the appearance of some progress. I think ESR is spot on https://en.wikipedia.org/wiki/Release_early,_release_often !

No further comment on that.

> 4) I would like to see support for Windows / MacOSX and more platforms. I want to use this library in https://github.com/tobimensch/aqemu . Is there any reason support for those platforms wasn't already added, besides that nobody has done the work?

MacOS X is supported very well, unfortunately not completely. Windows could be a nice goal when one has a business case.
Patches welcome.

> 5) I googled for "c c++ library process cpu mem usage" and similar terms, a few links and Stackoverflow threads came up, but libstatgrab was nowhere to be found. A helpful person on IRC made me aware of libstatgrab. It seems like libstatgrab's website and github page aren't optimized to be found by a search engine, yet. It would be a good idea to make mention of libstatgrab on those stackoverflow threads that came up, and I might do that later. I want to suggest working on the website, the github description and the README. Currently all the information that you're getting is "cross platform access to statistics about the system on which it's run". This isn't useful for search engine queries. You need to describe what kind of statistics exactly. For example "statistics about process cpu load and memory usage". Generally the more detailed a description you can give the better (it can be found).

We, at i-scream follow the "rock stable" approach and don't release few times a day to cherry picked pilot users as other projects are easily able to do.
Please realize, that all developers have a private life, too - and free development in spare time competes against time for family, children, relaxing, ...

Best regards
--
Jens Rehsack - rehsack@gmail.com

**Comment by tobimensch** [comment]
All points well taken. It wasn't meant to be taken personally, and I'm sorry if it came off that way.

1) I was indirectly pointing out that I consider libstatgrab an important/useful library, as there appear to be very few alternatives with the same objectives. (With different disadvantages)

2) Agreed. Didn't want to put down the OSes that are supported. In fact I'm a Linux user, so the most important OS for me personally is supported. As you pointed out Win/Mac are prominent in the desktop world, and the missing support is unfortunate, as I'm going to use libstatgrab in a desktop application.

3) I don't know why you're getting pissed at this. Looking at the commits, there shouldn't be any regressions. So what stands in the way of a minor release? Of course, it's YOUR choice (to make one or not to make one)! I'm happy about your fast response by the way, now I know this project isn't abandoned by any definition.

4) Ah, good to know, thanks! Looking at the source I saw two files named win32.h and win32.c. Is there limited support for Win32 already, or did someone try to add support for it, but it wasn't really completed?

5) You didn't really address this point, which is okay. I just think libstatgrab is a good project, and deservers to be found by more developers, and some text optimizations couldn't hurt in that way.

Thanks again for your instantaneous response. I'm looking forward to using this library, maybe even to adding Windows support, who knows.

Kind Regards

**Comment by rehsack** [comment]
> Am 15.06.2016 um 12:51 schrieb Tobi <notifications@github.com>:
> 
> All points well taken. It wasn't meant to be taken personally, and I'm sorry if it came off that way.
> 
> 1) I was indirectly pointing out that I consider libstatgrab an important/useful library, as there appear to be very few alternatives with the same objectives. (With different disadvantages)

There're probably more then obvious ...
* OMD deals with a check_mk which uses shell executes to grab those information.
* IBM's TSM has several approaches in deployed agents
* HP OpenView similar
* Nagios NRPE agents have per-system implementation of collecting statistics

But of course, very small provide them collected and with one API for all (most) systems :)

> 2) Agreed. Didn't want to put down the OSes that are supported. In fact I'm a Linux user, so the most important OS for me personally is supported. As you pointed out Win/Mac are prominent in the desktop world, and the missing support is unfortunate, as I'm going to use libstatgrab in a desktop application.
> 
> 3) I don't know why you're getting pissed at this. Looking at the commits, there shouldn't be any regressions. So what stands in the way of a minor release? Of course, it's YOUR choice (to make one or not to make one)! I'm happy about your fast response by the way, now I know this project isn't abandoned by any definition.

The point is, that release to have a release isn't reasonable.
An new release would bring no improvements for typical users, neither on Desktop/Server nor in DataCenter.
Just a handful of embedded users with crappy closed source drivers would have an advantage.

> 4) Ah, good to know, thanks! Looking at the source I saw two files named win32.h and win32.c. Is there limited support for Win32 already, or did someone try to add support for it, but it wasn't really completed?

Someone tried ages ago, but unfortunately one needs to have and develop on a windows to succeed.
Who is seriously willing to do that :P (I know some, but none of them are system addicted and they have other hobby's in there spare time).

> 5) You didn't really address this point, which is okay. I just think libstatgrab is a good project, and deservers to be found by more developers, and some text optimizations couldn't hurt in that way.

Sure, and sending patches will result in review / applying them ;)

> Thanks again for your instantaneous response. I'm looking forward to using this library, maybe even to adding Windows support, who knows.

We'll gladly approve any input :D

Cheers
--
Jens Rehsack - rehsack@gmail.com

**Comment by tobimensch** [comment]
> MacOS X is supported very well, unfortunately not completely. 

Do you what is missing for complete support?

> Someone tried ages ago, but unfortunately one needs to have and develop on a windows to succeed.
Who is seriously willing to do that :P (I know some, but none of them are system addicted and they have other hobby's in there spare time).

I have little experience with the Windows API myself. I could use my AQEMU created Windows VM to gain that experience and add that support. Admittedly it doesn't sound like one would have much fun implementing it. :P 

Thanks! Will send pull requests in an undefined future.

**Comment by rehsack** [comment]
> Am 15.06.2016 um 13:10 schrieb Tobi <notifications@github.com>:
> 
> > MacOS X is supported very well, unfortunately not completely.
> 
> Do you what is missing for complete support?

Not out-of-the-box, I played with Unix::Statgrab last weeks and stumbled over some missing details.
Maybe UDP packets dropped per second or something similar ...

If you seriously want to know, put me an issue for analyze in github and I'll see that I prove and create tickets to fix each finding.

> > Someone tried ages ago, but unfortunately one needs to have and develop on a windows to succeed.
> > Who is seriously willing to do that :P (I know some, but none of them are system addicted and they have other hobby's in there spare time).
> 
> I have little experience with the Windows API myself. I could use my AQEMU created Windows VM to gain that experience and add that support. Admittedly it doesn't sound like one would have much fun implementing it. :P
> 
> Thanks! Will send pull requests in an undefined future.

I developed a lot for Win32 at Windows 2000 ages - but the times have changed. Supported API is Win7+, no one who cares system health will seriously run Windows 2000 or XP anymore (without Platin support contract and know where the supporter's children are in school ^^ (that's joking, for BKA/NSA readers :P)).

Very likely the most data for Windows can be fetched with suitable WMI queries - if that approach is still there ...
My biggest blocker was the missing "autoconf for windows" - so I couldn't prove for deprecated or available API versions ...

Cheers
--
Jens Rehsack - rehsack@gmail.com

**Comment by tobimensch** [comment]
> I developed a lot for Win32 at Windows 2000 ages - but the times have changed. Supported API is Win7+, no one who cares system health will seriously run Windows 2000 or XP anymore (without Platin support contract and know where the supporter's children are in school ^^ (that's joking, for BKA/NSA readers :P)).

I have never used Win7+ so far. It's about time I make a VM for them.

> Very likely the most data for Windows can be fetched with suitable WMI queries - if that approach is still there ...

Okay, thanks for the pointer.

> My biggest blocker was the missing "autoconf for windows" - so I couldn't prove for deprecated or available API versions ...

I'm not very fond of autoconf. The combination of autoconf/Windows sounds like a nightmare. :D 

Closing this.

**Comment by rehsack** [comment]
> Am 15.06.2016 um 13:39 schrieb Tobi <notifications@github.com>:
> 
> [...]
> I'm not very fond of autoconf. The combination of autoconf/Windows sounds like a nightmare. :D

Maybe Config::AutoConf helps out :)

Cheers
--
Jens Rehsack - rehsack@gmail.com

**Comment by q2dg** [comment]
Well, I'll move on https://github.com/sysstat/sysstat

**Comment by rehsack** [comment]
Well, this might be a good info when you explain what improves the listed projects over libstatgrab.
