### ISSUE TITLE
`./configure --disable-man-build` ignored

### ISSUE THREAD

**Issue by ckaran** [i-scream/libstatgrab#83]
When building from source it appears that `./configure --disable-man-build` is being ignored; I get crashes when trying to build from source.

Steps to reproduce:
1. Get on a machine that doesn't have any of the documentation building tools installed, otherwise the build will succeed.
2. Clone from https://github.com/i-scream/libstatgrab.git
3. Checkout 897fedb9fdeab9934e92d072d6337eb061ce1e13
4. `./autogen`
5. `./configure --disable-man-build`
6. `make`

The build will fail with the following error:

```
Making all in docs
Making all in libstatgrab
make[3]: *** No rule to make target `statgrab.3', needed by `all-am'.  Stop.
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I can force the build to complete by finding and removing all mentions of the `docs` directory in `configure.ac` and the top-level `Makefile.am`, but as I understand it, I shouldn't have to because the `--disable-man-build` is supposed to take care of that for me.

**Comment by rehsack** [comment]
Building from checkouts is for maintainers only. You'll need additional maintainer tools - see README

**Comment by tdb** [comment]
To clarify what's going on here a bit: you're telling the build system not to generate the manual pages, which it correctly doesn't do. But you can't install libstatgrab without the manual pages. In a normal distribution tarball we include them pre-generated so this isn't a problem.

I suppose one could argue that this flag should completely ignore the manual pages, but maybe an additional flag should be used instead (`--disable-man`?).

**Comment by rehsack** [comment]
You can easily apply patches by using "patch -p1 <file-with-patch"

**Comment by ckaran** [comment]
OK, so your suggestion is that I grab the latest tarball, and then update it with whatever is in HEAD, correct?  If instead I unpack the tarball on top of the git repository, will that work as well?  My assumption is that git will only notice the generated files and updated files.  I can revert the updated files to whatever is in HEAD, and then everything should Just Work (TM).  Right? Or am I missing something?

The only reason for this method is that once I've unpacked the tarball on the working directory and then a `git checkout -- .` on it, I can then `git pull` at any time, and get the latest HEAD, and it should still compile correctly, which would be handy.

**Comment by rehsack** [comment]
For today: I strongly suggest working based on release tarball (and apply only those patches you really need)!

Generally: building from repository is for maintainers and developers only - in many circumstances users building from repository will be surprised (and rarely with something positive).

**Comment by tdb** [comment]
@ckaran can you try the patch in #85 against the latest master? It changes `--disable-man-build` to `--disable-man` which does as described above.

**Comment by ckaran** [comment]
Works perfectly!  Thanks!
