### ISSUE TITLE
sg_get_mem_stats() and friends don't document arguments

### ISSUE THREAD

**Issue by CorbinSimpsonAcquia** [i-scream/libstatgrab#86]
Hi!

`sg_get_mem_stats(size_t *entries)` doesn't have any documentation in the man page about what `entries` should be. All example code uses `NULL`, which makes sense given the previous API, but doesn't explain what `entries` could be if not `NULL`.

Thanks!

**Comment by rehsack** [comment]
Have a look at sg_intro(3) - e.g. via http://www.i-scream.org/libstatgrab/docs/sg_intro.3.html, does it explain your questions?

**Comment by CorbinSimpsonAcquia** [comment]
It does, thanks!
