### ISSUE TITLE
Building fails with error "No rule to make target `statgrab.3' "

### ISSUE THREAD

**Issue by edelmanjm** [i-scream/libstatgrab#88]
Make fails with the following error:

```
Making all in libstatgrab
make[3]: *** No rule to make target `statgrab.3', needed by `all-am'.  Stop.
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

- Operating system: *macOS 10.12.4*

**Comment by rehsack** [comment]
Please read the documentation for developers/maintainers when accessing the repository.

**Comment by edelmanjm** [comment]
Unfortunately I don't think I'm qualified as a developer or maintainer for this project. Is there somewhere else I should be looking for help other than this repository? Outside of the list of supported platforms I didn't see much documentation that'd be applicable to me; I did notice that macOS isn't supported, but I thought it might be close enough to BSD to work. Is there something I'm missing?

**Comment by rehsack** [comment]
In that case, plase download the released tarball for users from here: http://www.i-scream.org/libstatgrab/

**Comment by rehsack** [comment]
And well - it runs mostly fine on my Mac ;)

**Comment by edelmanjm** [comment]
Gotcha. [CPU-X's](https://github.com/X0rg/CPU-X/wiki/%5BHOW-TO%5D-Install-on-OS-X) Mac install instructions say to build from the source, so I assumed that was the intended method.

**Comment by rehsack** [comment]
Yes, from source - but not necessarily from repository :)

**Comment by edelmanjm** [comment]
Fair enough :). Build from the release, worked great. Now I just need to get CPU-X to build properly :|
