### ISSUE TITLE
cpu_stats.c:223]: (error) Resource leak: f

### ISSUE THREAD

**Issue by dcb314** [i-scream/libstatgrab#90]
Source code is

           if (proc_stat_cpu < 4 || proc_stat_cpu > 5) {
                RETURN_WITH_SET_ERROR("cpu", SG_ERROR_PARSE, "cpu");
            }

Some possible duplicates:

disk_stats.c:524]: (error) Resource leak: fh
network_stats.c:608]: (error) Resource leak: f

**Comment by rehsack** [comment]
Can you please describe the found resource leak?

**Comment by dcb314** [comment]
I am not sure what you are asking for, but the solution
might be a call to fclose( f), inside the if.

**Comment by rehsack** [comment]
I ask for the resource you found leaking. Since I do a bit more than libstatgrab, I do not have all the source code in mind and the earlier I understand a problem the higher the fix priority is rated ;)

**Comment by dcb314** [comment]
??

Source code file libstatgrab-0.91/src/libstatgrab/cpu_stats.c, line number 223.

My apologies for assuming that you know all the filenames of all the projects you support.
